### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kloczek** [wangyi-fudan/wyhash#112]
https://github.com/wangyi-fudan/wyhash/compare/wyhash_final...master shows +170 commits done since last release.
Do you have any plans to make new release?
What about change versioning convention to `<numeric.version.with.just.dots>`? 🤔

**Comment by wangyi-fudan** [comment]
done, thanks!

**Comment by kloczek** [comment]
Hmm .. I don't see any new git tag in https://github.com/wangyi-fudan/wyhash/tags.
Maybe you forgot to make `git push`? 🤔

**Comment by kloczek** [comment]
BTW new version like `1.0.0` will be perfectly fine with already present tags as numbers are at the end of the alphabet 😄

**Comment by kloczek** [comment]
gentle ping .. 🤔 
Still there is no new release tag in https://github.com/wangyi-fudan/wyhash/tags
